name: 打包ASG-tauri桌面应用
on: push

permissions:
  contents: write

jobs: 
  npm-build:
    name: build打包工作
    runs-on: windows-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 下载PNPM
        run:
          npm install pnpm
          
      - name: 安装依赖和项目打包
        run: |
          
          pnpm install
          pnpm run tauri-build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build-pages
          folder: src-tauri/target/release/bundle/msi