name: 打包ASG-tauri桌面应用
on: push

permissions:
  contents: write

jobs: 
   npm-build:
     name: build打包工作
     runs-on: windows-latest
     steps:
     - name: 读取仓库内容
       uses: actions/checkout@v4

     - name: 安装依赖 和 项目打包
       run: 
         npm run install
         npm run build

     - name: 部署
       uses: JamesIves/github-pages-deploy-action@4
       with:
         branch: build-pages
         folder: dist